/* eslint-disable @typescript-eslint/no-misused-promises */
import Head from "next/head";
import HomeComponent from "@/components/Home";
export default function Home() {
  return (
    <>
      <Head>
        <title>Drive Clone with Faid</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="https://logos.textgiraffe.com/logos/logo-name/Terence-designstyle-cartoon-m.png" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          {/* <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
           Welcome {session?.user.name}
          </h1> */}
          <HomeComponent />
        </div>
      </main>
    </>
  );
}
